# theme: jekyll-theme-minimal
# remote_theme: jekyll/minima
theme: minima

title: Формальные методы разработки программ

header_pages:
  - astraver.md
  - rodin.md
  - anis.md

description: ""

exclude:
  - slides/floyd_partial/.venv
  - slides/floyd_term/.venv
  - "**/.venv"
  - "**/lib64"
